import { Table, Column, Model, DataType, ForeignKey } from 'sequelize-typescript';
import { Lesson } from 'src/lesson/lesson.schema';
import { User } from 'src/user/user.schema';

@Table
export class UserLesson extends Model<UserLesson> {
  @ForeignKey(() => User)
  @Column({
    type: DataType.STRING,
    allowNull: false,
  })
  userId: string;

  @ForeignKey(() => Lesson)
  @Column({
    type: DataType.STRING,
    allowNull: false,
  })
  lessonId: number; //this is assuming we use the autogenerated key

  @Column({
    type: DataType.STRING,
    allowNull: false,
  })
  stepCompleted: number;
}
